name: Deploy App to VPS

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: SSH into VPS and pull & run Docker image
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
          # Navigate to the correct directory
          cd ~/projects/portfolio-analyzer

          # Pull the latest Docker image
          echo "Pulling the latest Docker image..."
          docker pull ghcr.io/kbberendsen/portfolio-analyzer:latest

          # Stop any running containers
          echo "Stopping any running containers..."
          docker-compose down

          # Start the new container
          echo "Starting the new container..."
          docker-compose up -d --build
        EOF
