name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GENERAL_TOKEN }}
        registry: ghcr.io

    - name: Build the Docker image
      run: |
        docker compose -f docker-compose-dev.yaml up --force-recreate -d --build
        docker tag portfolio-analyzer:latest ghcr.io/kbberendsen/portfolio-analyzer:latest
    
    - name: Push the Docker image to GitHub Container Registry
      run: |
        docker push ghcr.io/kbberendsen/portfolio-analyzer:latest
