name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GENERAL_TOKEN }}
        registry: ghcr.io

    - name: Build Docker image from main branch
      run: docker build -t ghcr.io/kbberendsen/portfolio-analyzer:latest .

    - name: Push Docker image to GitHub Container Registry
      run: docker push ghcr.io/kbberendsen/portfolio-analyzer:latest
